### ISSUE TITLE
Missing directory logs and camera.log file

### ISSUE THREAD

**Issue by meteorkees** [IanCassTwo/rpicam-ascom-alpaca#1]
Installed according readme file on Raspberry pi 3B+ / Bullseye 32bit. At first run of app.py error popped up. Missing directory camera.log. 

Solved issue by adding a directory 'logs' inside directory 'rpicam-ascom-alpaca. Inside /logs create empty text file camera.log
After that, running like a charm!
K.

**Comment by IanCassTwo** [comment]
Fixed. Git removed it because it doesn't like empty directories
