### ISSUE TITLE
"Exception: Unknown camera imx519" and others such as imx462

### ISSUE THREAD

**Issue by rleyden559** [IanCassTwo/rpicam-ascom-alpaca#4]
I notice that you comment in SensorFactory.py that adding more cameras is on the todo list.  I'm particularly interested in the imc462 which has good low light performance .  For now, I'm testing with the Arducam imx519.
I made simple changes to  SensorFactory.py adding imx519  following the template of imx477 and then minimally edited and renamed IMX477.py to IMX519.py.  That ran until I tried to open the stream with sharpcap when an exception  "KeyError: 'SensorTemperature'".   
I suppose I will need to actually put in real values into IMX519.py.  Suggestions would be appreciated.

**Comment by IanCassTwo** [comment]
Do you have these other sensors attached to a Raspberry Pi and working with libcamera?

**Comment by IanCassTwo** [comment]
Comment out lines 544 to 547 in camera.py. I suspect that's what's causing your issue. If that works, we can put in a better fix. The other values in IMX519.py e.g. Electrons per ADU and FWC can be gained from the Sharpcap sensor analysis, however they're really not critical and I'm not even sure any software uses them. You should probably make best effort to get them vaguely correct though.

**Comment by rleyden559** [comment]
Do you have these other sensors attached to a Raspberry Pi and working with libcamera?
.........
The short answer is yes.  They both can be made to appear on the 
Raspberry Pi as /dev/video0.  For the imx519 all that is required, at 
least since mid Bullseye OS , is to add  dtoverlay=imx519 to config.txt.

The long answer is that I purchased these cameras for Arducam in 2022 as 
a launch customer for what seemed like a good deal at the time.  Arducam 
supplied drivers which were not "up streamed" (a term from PI engineer 
on their forum.  This may be less of an issue over time but since 
Raspberry Pi sells it own line of cameras I can imagine that Arducam's 
cameras will never quite work as well.

Here's a list of the Arducam cameras I own.

    Arducam 462- funky daughter board, new orders don’t have daughter 
board. 2MP resolution  Same driver Sony STARVIS IMX290 and IMX462
     imx 519 auto-focus
     imx 519 auto focus nior  (no IR)
     64MP Auto Focus Camera Module  Image Sensor    OV64A40

My initial testing of the imx462 blew me away.  I swapped out the stock 
wide angle lens for a 16 mm (mildly telephoto with the small sensor) and 
got passable deep sky images of Andromeda.  However, the daughter board 
(which is a hardware kludge to get software compatibility)   makes 
integrating it with software tedious.  So, I ordered a version from 
Amazon ($33) that is supposed to "just work"  
.https://www.amazon.com/dp/B0B5G84PQ8?psc=1&ref=ppx_yo2ov_dt_b_product_details 
<https://www.amazon.com/dp/B0B5G84PQ8?psc=1&ref=ppx_yo2ov_dt_b_product_details> 


The imx462 is the sensor in a number of commercial telescope cameras, 
usually described as "planetary cameras"  .  I find it surprising that 
it hasn't been mentioned much in that application by Pi users.

**Comment by rleyden559** [comment]
Commenting out lines 544 to 547 worked.  I now get the camera to load into SharpCap.  
I get a message on the pi terminal "ERROR NotImplementedException: Property or method not implemented.".  But there is a recognizable image on Sharpcap.
 I will try to get  IMX519.py closer to  the actual hardware.  I cannot find "unpacked RAW format" or "Bayer Pattern" in the spec sheet for imx519, at least not  using the syntax similar to the imx477 example.
The new im462 camera from Amazon is arriving later today, so I will probably switch over to fine tuning that since it is the real target for your app.

**Comment by IanCassTwo** [comment]
I think you can run "print_camera_information.py" that's included in my source tree in the util directory. It will output loads of stuff but you want to find the json array printed towards the end showing all the different resolutions & modes. Look for something like ...

{'bit_depth': 10,
  'crop_limits': (0, 0, 3280, 2464),
  'exposure_limits': (75, 11766829, None),
  'format': SRGGB10_CSI2P,
  'fps': 21.19,
  'size': (3280, 2464),
  'unpacked': 'SRGGB10'}

The "unpacked" field will give you the right value to put into your IMX519.py.

**Comment by rleyden559** [comment]
Wow! That was easy.
For those curious, here is the output of  print_camera_information.py.
..........
Found 1 cameras.

Camera 0:
{'Id': '/base/soc/i2c0mux/i2c@1/imx519@1a',
 'Location': 2,
 'Model': 'imx519',
 'Rotation': 0}

Camera properties:
{'ColorFilterArrangement': 0,
 'Location': 2,
 'Model': 'imx519',
 'PixelArrayActiveAreas': [(8, 48, 4656, 3496)],
 'PixelArraySize': (4656, 3496),
 'Rotation': 0,
 'ScalerCropMaximum': (0, 0, 0, 0),
 'SystemDevices': (20750, 20751, 20739, 20740, 20741),
 'UnitCellSize': (1220, 1220)}

Raw sensor modes:
[{'bit_depth': 10,
  'crop_limits': (1048, 1042, 2560, 1440),
  'exposure_limits': (287, None),
  'format': SRGGB10_CSI2P,
  'fps': 80.01,
  'size': (1280, 720),
  'unpacked': 'SRGGB10'},
 {'bit_depth': 10,
  'crop_limits': (408, 674, 3840, 2160),
  'exposure_limits': (282, 118428825, None),
  'format': SRGGB10_CSI2P,
  'fps': 60.05,
  'size': (1920, 1080),
  'unpacked': 'SRGGB10'},
 {'bit_depth': 10,
  'crop_limits': (0, 0, 4656, 3496),
  'exposure_limits': (305, 118430097, None),
  'format': SRGGB10_CSI2P,
  'fps': 30.0,
  'size': (2328, 1748),
  'unpacked': 'SRGGB10'},
 {'bit_depth': 10,
  'crop_limits': (408, 672, 3840, 2160),
  'exposure_limits': (491, 127960311, None),
  'format': SRGGB10_CSI2P,
  'fps': 18.0,
  'size': (3840, 2160),
  'unpacked': 'SRGGB10'},
 {'bit_depth': 10,
  'crop_limits': (0, 0, 4656, 3496),
  'exposure_limits': (592, 206049113, None),
  'format': SRGGB10_CSI2P,
  'fps': 9.0,
  'size': (4656, 3496),
  'unpacked': 'SRGGB10'}]

Camera controls:
{'AeConstraintMode': (0, 3, 0),
 'AeEnable': (False, True, None),
 'AeExposureMode': (0, 3, 0),
 'AeMeteringMode': (0, 3, 0),
 'AfMetering': (0, 1, 0),
 'AfMode': (0, 2, 0),
 'AfPause': (0, 2, 0),
 'AfRange': (0, 2, 0),
 'AfSpeed': (0, 1, 0),
 'AfTrigger': (0, 1, 0),
 'AfWindows': ((0, 0, 0, 0), (65535, 65535, 65535, 65535), (0, 0, 0, 0)),
 'AnalogueGain': (1.0, 16.0, None),
 'AwbEnable': (False, True, None),
 'AwbMode': (0, 7, 0),
 'Brightness': (-1.0, 1.0, 0.0),
 'ColourGains': (0.0, 32.0, None),
 'Contrast': (0.0, 32.0, 1.0),
 'ExposureTime': (592, 206049113, None),
 'ExposureValue': (-8.0, 8.0, 0.0),
 'FrameDurationLimits': (111092, 248572499, None),
 'LensPosition': (0.0, 32.0, 1.0),
 'NoiseReductionMode': (0, 4, 0),
 'Saturation': (0.0, 32.0, 1.0),
 'ScalerCrop': ((0, 0, 64, 64), (0, 0, 4656, 3496), (0, 2, 4656, 3492)),
 'Sharpness': (0.0, 16.0, 1.0)}

Exposure time:
  min: 592, max: 206049113, default: None

AnalogGain:
  min: 1.0, max: 16.0, default: None

**Comment by rleyden559** [comment]
I received the imx462 from Amazon today.  It uses the imx290 driver (. dtoverlay=imx290,clock-frequency=74250000)  Quick bench testing showed it performed as expected, 114 sec exposure in a dark room with only the Pi LED's was fully illuminated.
The output of print_camera_information.py is below;
.........
Found 1 cameras.

Camera 0:
{'Id': '/base/soc/i2c0mux/i2c@1/imx290@1a',
 'Location': 2,
 'Model': 'imx290',
 'Rotation': 0}

Camera properties:
{'ColorFilterArrangement': 0,
 'Location': 2,
 'Model': 'imx290',
 'PixelArrayActiveAreas': [(12, 8, 1920, 1080)],
 'PixelArraySize': (1945, 1097),
 'Rotation': 0,
 'ScalerCropMaximum': (0, 0, 0, 0),
 'SystemDevices': (20750, 20738, 20739, 20740),
 'UnitCellSize': (2900, 2900)}

Raw sensor modes:
[{'bit_depth': 10,
  'crop_limits': (320, 180, 1280, 720),
  'exposure_limits': (22, None),
  'format': SRGGB10_CSI2P,
  'fps': 60.0,
  'size': (1280, 720),
  'unpacked': 'SRGGB10'},
 {'bit_depth': 10,
  'crop_limits': (0, 0, 1920, 1080),
  'exposure_limits': (14, 115686250, None),
  'format': SRGGB10_CSI2P,
  'fps': 60.0,
  'size': (1920, 1080),
  'unpacked': 'SRGGB10'},
 {'bit_depth': 12,
  'crop_limits': (320, 180, 1280, 720),
  'exposure_limits': (22, 115686258, None),
  'format': SRGGB12_CSI2P,
  'fps': 60.0,
  'size': (1280, 720),
  'unpacked': 'SRGGB12'},
 {'bit_depth': 12,
  'crop_limits': (0, 0, 1920, 1080),
  'exposure_limits': (14, 115686250, None),
  'format': SRGGB12_CSI2P,
  'fps': 60.0,
  'size': (1920, 1080),
  'unpacked': 'SRGGB12'}]

Camera controls:
{'AeConstraintMode': (0, 3, 0),
 'AeEnable': (False, True, None),
 'AeExposureMode': (0, 3, 0),
 'AeMeteringMode': (0, 3, 0),
 'AnalogueGain': (1.0, 31.62277603149414, None),
 'AwbEnable': (False, True, None),
 'AwbMode': (0, 7, 0),
 'Brightness': (-1.0, 1.0, 0.0),
 'ColourGains': (0.0, 32.0, None),
 'Contrast': (0.0, 32.0, 1.0),
 'ExposureTime': (14, 115686250, None),
 'ExposureValue': (-8.0, 8.0, 0.0),
 'FrameDurationLimits': (16666, 115687148, None),
 'NoiseReductionMode': (0, 4, 0),
 'Saturation': (0.0, 32.0, 1.0),
 'ScalerCrop': ((0, 0, 64, 64), (0, 0, 1920, 1080), (240, 0, 1440, 1080)),
 'Sharpness': (0.0, 16.0, 1.0)}

Exposure time:
  min: 14, max: 115686250, default: None

AnalogGain:
  min: 1.0, max: 31.62277603149414, default: None
..........
My first attempt at IMX290.py crashed Sharpcap (Pi terminal said 
"2024-03-14T02:46:09.617 ERROR NotImplementedException: Property or method not implemented." App.py did not crash so I think it is a system message.  I would not be surprised if it is a driver issue.
Here is IMX290.py
.............
from sensor.sensor import Sensor
from sensor.bayeroffset import BayerOffset

class IMX290(Sensor):
    def __init__(self):
        super().__init__(
            'imx290',                               # Name  all params guessed 3-13-24  rl
            1920,                                   # X Resolution
            1080,                                   # Y Resolution 
            16,                                     # Bits per pixel. Note, even though the sensor is 12bits, we're sending as 16
            2,                                      # Binning. Sensor must have a resolution equal to resolution divided by this number
            2.90,                                   # Native pixel size
            16,                                     # Max gain. Min gain is always zero
            0.00006,                                # Min exposure (secs)
            200,                                    # Max exposure (secs)
            [4.7,3.7,2.6,2.0,1.4,                   # Electrons per ADU. This should be an array of size 0 to <max gain>.                
             1.1,0.9,0.8,0.7,0.6,                   # Find the e/ADU values from Sharpcap sensor analysis
             0.6,0.5,0.4,0.4,0.3,
             0.3,0.3],                            
            [19403, 18370, 17350, 16342, 15347,     # Full well capacity. This should be an array of size 0 to <max gain>.
             14363, 13391, 12431, 11483, 10547,     # Fine the full well capacity values from Sharpcap sensor analysis
             9623, 8711, 7811, 6923, 6047, 
             5183, 4331],
            'SRGGB10',                              # unpacked RAW format
            BayerOffset.create_instance('BGGR')     # Bayer Pattern                   
        )
......
I will be away until next week and I'll try a few more things then, for example seeing how the camera behaves with other streaming apps (my guess -poorly)

**Comment by IanCassTwo** [comment]
Binning should be 1 for this camera because it doesn't have a binning mode. Also, RAW format is SRGGB12. Max exposure is 115 and min exposure is 0.000014.

**Comment by rleyden559** [comment]
With corrections to IMX290.py Sharpcap now displays proper image and seems stable.  This is despite system error messages on pi terminal which possibly could be ignored.
I will need to test more thoroughly and report back.
Thanks.

**Comment by IanCassTwo** [comment]
Great, feel free to submit a pull request with your changes so we can get these integrated
