### ISSUE TITLE
Camera downnoad fails for object reference not set

### ISSUE THREAD

**Issue by tschoenfelder** [IanCassTwo/rpicam-ascom-alpaca#5]
Hello,

thank you for this awesome work!

I have Raspi 5 with 64 bit latest Raspberry Pi OS Lite.
My camera is a HQ which is working via the RPICAM modules.
Starting app.py seems to be OK:
`(rpicam-ascom-alpaca) torsten@rasppiserver3:~/rpicam-ascom-alpaca$ python3 app.py
[215:42:25.643565737] [51602]  INFO Camera camera_manager.cpp:325 libcamera v0.3.2+27-7330f29b
[215:42:25.651265286] [51608]  INFO RPI pisp.cpp:695 libpisp version v1.0.7 28196ed6edcf 29-08-2024 (16:33:32)
[215:42:25.660582419] [51608]  INFO RPI pisp.cpp:1154 Registered camera /base/axi/pcie@120000/rp1/i2c@80000/imx477@1a to CFE device /dev/media3 and ISP device /dev/media0 using PiSP variant BCM2712_C0
[camera.log](https://github.com/user-attachments/files/17449634/camera.log)
[config.zip](https://github.com/user-attachments/files/17449637/config.zip)
`
I followed the readme connecting from NINA, which seems to work.  Image taking from NINA starts, but end in an error:
ASCOM driver error: "Object reference not set to an instance of an object" and
Error camera download failed Exposure time 30s, Type snapshot, gain:0 Filter: (Nothing listed).
The logs (in debug mode) are attached.

Any clue, how to continue?

thank you!

Best rgeards, Torsten

**Comment by IanCassTwo** [comment]
No idea what your issue is here. This is working on my setup and for many others so it's got to be something peculiar to your setup

**Comment by DanielDC88** [comment]
I've just reinstalled this after the SD card I was previously using died

I'm now getting this issue as well having installed raspberry pi os lite. I imagine it's got something to do with lite.

Also, the pip3 install command threw a warning:

`pi@pi4astro:~ $ pip3 install falcon toml orjson
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.`

Will try installing non-lite OS and feedback...

**Comment by DanielDC88** [comment]
Same issue with a fresh install of non-lite pios, perhaps related to https://github.com/IanCassTwo/rpicam-ascom-alpaca/issues/8
