### ISSUE TITLE
Using 16-bit when ADU is 12-bit?

### ISSUE THREAD

**Issue by DanielDC88** [IanCassTwo/rpicam-ascom-alpaca#6]
Hi, I've noticed the FITS files I get from this in NINA are 16-bit, but really shouldn't they be 12-bit based on the image sensor present in the Pi HQ camera I'm using?

https://www.sony-semicon.com/files/62/pdf/p-13_IMX477-AACK_Flyer.pdf

Wondering if this is a setting on my end or something fundamental to the driver. Thanks!

**Comment by IanCassTwo** [comment]
I don't scale the data in this driver. I pass them to NINA as 12bits inside a 16bit data length (so 8 wasted bits). See line 278 in shr.py. Nina has an option to enable bit scaling (in options/equipment/advanced settings). Not sure if that's what you're seeing?

**Comment by IanCassTwo** [comment]
Ok, seems I *do* scale it after all in camera.py line 563. Not sure why I did that. You can try to replace line 563 with array = array.view(np.uint16) to disable the scaling and see what happens

**Comment by DanielDC88** [comment]
That worked, thank you. Would it make sense / be possible to send the data as a 12 bpp image, as it is still showing as 16 bit in ASTAP?

**Comment by IanCassTwo** [comment]
I don't think there's a way to send the data as 12bit data. It's either 8bits or 16bits. However perhaps there's a way to indicate to the receiving app that it's meant to be 12bit. I'll take a look.

**Comment by DanielDC88** [comment]
Thanks. I think it would be good to send it natively as 12 bits as you'll not only be getting the true counts but also potentially saving 25% disk space.

With the change a completely blown out image's histogram is way out to the left in Nina, I managed to fix this by manually changing the bit depth:
![image](https://github.com/user-attachments/assets/1fb051c6-8c79-427b-a4be-dd7c25b76dc5)

**Comment by IanCassTwo** [comment]
I've suggested several times that we allow a packed bit image format in ASCOM which would allow us to send 12bit data. Remember, bytes are 8 bits, so to send 12 bits, you have to send 8 of those bits in 1 byte and then overflow into 4 bits of the next byte, and so on. I'm told ASCOM will not implement this, so we're limited to 8 or 16bits. 

If you tell NINA it's 12 bits, does it save a 12bit FIT?
